/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogKomplainIndexRouteImport } from './routes/log-komplain/index'
import { Route as LauncherIndexRouteImport } from './routes/launcher/index'
import { Route as LauncherRealIndexRouteImport } from './routes/launcher/realIndex'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogKomplainIndexRoute = LogKomplainIndexRouteImport.update({
  id: '/log-komplain/',
  path: '/log-komplain/',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherIndexRoute = LauncherIndexRouteImport.update({
  id: '/launcher/',
  path: '/launcher/',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherRealIndexRoute = LauncherRealIndexRouteImport.update({
  id: '/launcher/realIndex',
  path: '/launcher/realIndex',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/launcher/realIndex': typeof LauncherRealIndexRoute
  '/launcher': typeof LauncherIndexRoute
  '/log-komplain': typeof LogKomplainIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/launcher/realIndex': typeof LauncherRealIndexRoute
  '/launcher': typeof LauncherIndexRoute
  '/log-komplain': typeof LogKomplainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/launcher/realIndex': typeof LauncherRealIndexRoute
  '/launcher/': typeof LauncherIndexRoute
  '/log-komplain/': typeof LogKomplainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/launcher/realIndex' | '/launcher' | '/log-komplain'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/launcher/realIndex' | '/launcher' | '/log-komplain'
  id: '__root__' | '/' | '/launcher/realIndex' | '/launcher/' | '/log-komplain/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LauncherRealIndexRoute: typeof LauncherRealIndexRoute
  LauncherIndexRoute: typeof LauncherIndexRoute
  LogKomplainIndexRoute: typeof LogKomplainIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-komplain/': {
      id: '/log-komplain/'
      path: '/log-komplain'
      fullPath: '/log-komplain'
      preLoaderRoute: typeof LogKomplainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher/': {
      id: '/launcher/'
      path: '/launcher'
      fullPath: '/launcher'
      preLoaderRoute: typeof LauncherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher/realIndex': {
      id: '/launcher/realIndex'
      path: '/launcher/realIndex'
      fullPath: '/launcher/realIndex'
      preLoaderRoute: typeof LauncherRealIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LauncherRealIndexRoute: LauncherRealIndexRoute,
  LauncherIndexRoute: LauncherIndexRoute,
  LogKomplainIndexRoute: LogKomplainIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
