/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplateIndexRouteImport } from './routes/template/index'
import { Route as OcrIndexRouteImport } from './routes/ocr/index'
import { Route as LogsIndexRouteImport } from './routes/logs/index'
import { Route as LogKomplainIndexRouteImport } from './routes/log-komplain/index'
import { Route as LauncherIndexRouteImport } from './routes/launcher/index'
import { Route as BroadbandIndexRouteImport } from './routes/broadband/index'
import { Route as LauncherRealIndexRouteImport } from './routes/launcher/realIndex'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateIndexRoute = TemplateIndexRouteImport.update({
  id: '/template/',
  path: '/template/',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrIndexRoute = OcrIndexRouteImport.update({
  id: '/ocr/',
  path: '/ocr/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogKomplainIndexRoute = LogKomplainIndexRouteImport.update({
  id: '/log-komplain/',
  path: '/log-komplain/',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherIndexRoute = LauncherIndexRouteImport.update({
  id: '/launcher/',
  path: '/launcher/',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadbandIndexRoute = BroadbandIndexRouteImport.update({
  id: '/broadband/',
  path: '/broadband/',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherRealIndexRoute = LauncherRealIndexRouteImport.update({
  id: '/launcher/realIndex',
  path: '/launcher/realIndex',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/launcher/realIndex': typeof LauncherRealIndexRoute
  '/broadband': typeof BroadbandIndexRoute
  '/launcher': typeof LauncherIndexRoute
  '/log-komplain': typeof LogKomplainIndexRoute
  '/logs': typeof LogsIndexRoute
  '/ocr': typeof OcrIndexRoute
  '/template': typeof TemplateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/launcher/realIndex': typeof LauncherRealIndexRoute
  '/broadband': typeof BroadbandIndexRoute
  '/launcher': typeof LauncherIndexRoute
  '/log-komplain': typeof LogKomplainIndexRoute
  '/logs': typeof LogsIndexRoute
  '/ocr': typeof OcrIndexRoute
  '/template': typeof TemplateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/launcher/realIndex': typeof LauncherRealIndexRoute
  '/broadband/': typeof BroadbandIndexRoute
  '/launcher/': typeof LauncherIndexRoute
  '/log-komplain/': typeof LogKomplainIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/ocr/': typeof OcrIndexRoute
  '/template/': typeof TemplateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/launcher/realIndex'
    | '/broadband'
    | '/launcher'
    | '/log-komplain'
    | '/logs'
    | '/ocr'
    | '/template'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/launcher/realIndex'
    | '/broadband'
    | '/launcher'
    | '/log-komplain'
    | '/logs'
    | '/ocr'
    | '/template'
  id:
    | '__root__'
    | '/'
    | '/launcher/realIndex'
    | '/broadband/'
    | '/launcher/'
    | '/log-komplain/'
    | '/logs/'
    | '/ocr/'
    | '/template/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LauncherRealIndexRoute: typeof LauncherRealIndexRoute
  BroadbandIndexRoute: typeof BroadbandIndexRoute
  LauncherIndexRoute: typeof LauncherIndexRoute
  LogKomplainIndexRoute: typeof LogKomplainIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  OcrIndexRoute: typeof OcrIndexRoute
  TemplateIndexRoute: typeof TemplateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/': {
      id: '/template/'
      path: '/template'
      fullPath: '/template'
      preLoaderRoute: typeof TemplateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr/': {
      id: '/ocr/'
      path: '/ocr'
      fullPath: '/ocr'
      preLoaderRoute: typeof OcrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-komplain/': {
      id: '/log-komplain/'
      path: '/log-komplain'
      fullPath: '/log-komplain'
      preLoaderRoute: typeof LogKomplainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher/': {
      id: '/launcher/'
      path: '/launcher'
      fullPath: '/launcher'
      preLoaderRoute: typeof LauncherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadband/': {
      id: '/broadband/'
      path: '/broadband'
      fullPath: '/broadband'
      preLoaderRoute: typeof BroadbandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher/realIndex': {
      id: '/launcher/realIndex'
      path: '/launcher/realIndex'
      fullPath: '/launcher/realIndex'
      preLoaderRoute: typeof LauncherRealIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LauncherRealIndexRoute: LauncherRealIndexRoute,
  BroadbandIndexRoute: BroadbandIndexRoute,
  LauncherIndexRoute: LauncherIndexRoute,
  LogKomplainIndexRoute: LogKomplainIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  OcrIndexRoute: OcrIndexRoute,
  TemplateIndexRoute: TemplateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
